/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airlinepro;

/**
 *
 * @author Muasawenkosi
 */
public class ClientLoginandSgnUp extends javax.swing.JFrame {

    /**
     * Creates new form ClientLoginandSgnUp
     */
    public ClientLoginandSgnUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        PassengerMenu = new javax.swing.JMenu();
        itemLoginPassenger = new javax.swing.JMenuItem();
        itemSignUpPassenge = new javax.swing.JMenuItem();
        HomeItem = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        UpdateProfile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PassengerMenu.setText("Passanger");
        PassengerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassengerMenuActionPerformed(evt);
            }
        });

        itemLoginPassenger.setText("LogIn");
        itemLoginPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginPassengerActionPerformed(evt);
            }
        });
        PassengerMenu.add(itemLoginPassenger);

        itemSignUpPassenge.setText("SignUp");
        itemSignUpPassenge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSignUpPassengeActionPerformed(evt);
            }
        });
        PassengerMenu.add(itemSignUpPassenge);

        jMenuBar1.add(PassengerMenu);

        HomeItem.setText("Options");

        jMenuItem3.setText("Home");
        HomeItem.add(jMenuItem3);

        UpdateProfile.setText("Update");
        HomeItem.add(UpdateProfile);

        jMenuBar1.add(HomeItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassengerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassengerMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PassengerMenuActionPerformed

    private void itemLoginPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginPassengerActionPerformed
        // TODO add your handling code here:
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_itemLoginPassengerActionPerformed

    private void itemSignUpPassengeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSignUpPassengeActionPerformed
        // TODO add your handling code here:
        SignUpFrame signUp = new SignUpFrame();
        signUp.setVisible(true);
    }//GEN-LAST:event_itemSignUpPassengeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientLoginandSgnUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientLoginandSgnUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientLoginandSgnUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientLoginandSgnUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientLoginandSgnUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu HomeItem;
    private javax.swing.JMenu PassengerMenu;
    private javax.swing.JMenuItem UpdateProfile;
    private javax.swing.JMenuItem itemLoginPassenger;
    private javax.swing.JMenuItem itemSignUpPassenge;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
