/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.airlinepro;

/**
 *
 * @author Muasawenkosi
 */
import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.util.Random;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

public class SignUp extends javax.swing.JPanel {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
         clearTextFields();
    }
    private void clearTextFields() {
        txtClientName.setText("");
        txtClientSurname.setText("");
        txtClientID.setText("");
        txtClientPassport.setText("");
        txtClientContact.setText("");
        txtClientAddress.setText("");
        txtClientPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClientPassword = new javax.swing.JPasswordField();
        txtClientName = new javax.swing.JTextField();
        txtClientSurname = new javax.swing.JTextField();
        txtClientID = new javax.swing.JTextField();
        txtClientPassport = new javax.swing.JTextField();
        txtClientContact = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        txtClientAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Names:");

        jLabel2.setText("Surname:");

        jLabel3.setText("ID Number:");

        jLabel4.setText("Passport ID:");

        jLabel5.setText("Contact:");

        jLabel6.setText("Address:");

        txtClientPassword.setText("jPasswordField1");

        txtClientName.setText("jTextField1");

        txtClientSurname.setText("jTextField2");

        txtClientID.setText("jTextField3");

        txtClientPassport.setText("jTextField4");

        txtClientContact.setText("jTextField5");

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        txtClientAddress.setText("jTextField6");

        jLabel7.setText("Password:");

        jLabel8.setText("Sign Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtClientName)
                    .addComponent(txtClientSurname)
                    .addComponent(txtClientID)
                    .addComponent(txtClientPassport)
                    .addComponent(txtClientContact)
                    .addComponent(txtClientPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtClientAddress))
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClientSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtClientPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtClientContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(55, 55, 55)
                .addComponent(btnSignUp)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        String name = txtClientName.getText();
        String surname = txtClientSurname.getText();
        String idNumber = txtClientID.getText();
        String passportID = txtClientPassport.getText();
        String contact = txtClientContact.getText();
        String address = txtClientAddress.getText();
        String password = new String(txtClientPassword.getPassword()); 
        //Validation 
        if (name.isEmpty() || surname.isEmpty() || idNumber.isEmpty() || passportID.isEmpty() || contact.isEmpty() || address.isEmpty() || password.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "All fields are required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (idNumber.length() != 13)
        {

            JOptionPane.showMessageDialog(this, "ID number must be 13 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (passportID.length() != 10) {
           
            JOptionPane.showMessageDialog(this, "Passport number must be 10 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!isUniqueIDAndPassport(idNumber, passportID)) 
        {
                
             JOptionPane.showMessageDialog(this, "ID number or passport number already exists. Please provide unique values.", "Error", JOptionPane.ERROR_MESSAGE);
              return; 
        }

            
           saveToFile(name, surname, idNumber, passportID, contact, address, password);

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void saveToFile(String name, String surname, String idNumber, String passportID, String contact, String address, String password) {
        String filename = "ClientProfile.txt"; 
        String userID = generateUserID(name, surname);

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename, true))) {

            writer.write(name + "," + surname + "," + idNumber + "," + passportID + "," + contact + "," + address + "," + password + "," + userID + "\n");
            JOptionPane.showMessageDialog(this, "Thank you for signing up.\nYour User ID is "+userID , "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error in Signing Up: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        private String generateUserID(String name, String surname) 
        {
            Random ran = new Random();
            String OneLetterNAME = name.substring(0, Math.min(name.length(), 1));
            String OneLeterSur = surname.substring(0, Math.min(surname.length(), 1));
            String randomDigits = String.format("%04d", ran.nextInt(10000));
            
            return OneLetterNAME.toUpperCase() + OneLeterSur.toUpperCase() + randomDigits;
        }
        private boolean isUniqueIDAndPassport(String idNumber, String passportID)
        {
            boolean isUnique = true;
            String filename = "ClientProfile.txt";

            try (BufferedReader reader = new BufferedReader(new FileReader(filename))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(",");
                    if (parts.length >= 4 && (parts[2].equals(idNumber) || parts[3].equals(passportID))) {
                        isUnique = false;
                        break;
                    }
                }
            } catch (IOException e) {
                
               
                JOptionPane.showMessageDialog(this, "Error reading user details file.", "Error", JOptionPane.ERROR_MESSAGE);
                isUnique = false; 
            }

           return isUnique;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtClientAddress;
    private javax.swing.JTextField txtClientContact;
    private javax.swing.JTextField txtClientID;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtClientPassport;
    private javax.swing.JPasswordField txtClientPassword;
    private javax.swing.JTextField txtClientSurname;
    // End of variables declaration//GEN-END:variables
}
